### ISSUE TITLE
Server failed to listen: listen tcp 127.0.0.1:8790: bind: address already in use

### ISSUE THREAD

**Issue by zhaytee** [GoogleCloudPlatform/esp-v2#363]
Just upgraded our ESPv1 sidecar deployment to ESPv2. Pretty excited about it, thanks for getting the sidecar mode working!

We serve multiple Cloud Endpoints services from each k8s pod. This pattern worked with ESPv1. However, ESPv2 seems to listen on a port called DiscoveryPort (default 8790). This causes a conflict with other ESPv2 instances running on the same pod:

```
Server failed to listen: listen tcp 127.0.0.1:8790: bind: address already in use
```

I'm unable to find a way to manually set that port, e.g. via a cli option or similar.

Is there a recommended path forward here? The only thing I can think of is creating a completely separate k8s Deployment for each of our Cloud Endpoints services, which would be undesirable in our particular case. So, hoping there's a better way forward.

Thank you!

**Comment by TAOXUY** [comment]
Hi zhaytee,

You are right. Right now, ESPv2 uses fixed 8790 as the ads port, which is a port used by the control plane of ESPv2. We can expose a flag to use other port to fix this problem.

**Comment by qiwzhang** [comment]
My understanding is: 8790 is a local port inside the ESPv2 container.  It should not conflict with other ESPv2 containers in the same pod.  Am i wrong?

**Comment by TAOXUY** [comment]
The problem is that multi-containers in one pod share one IP address and same `localhost` so ESPv2 may have port conflicts with other containers. [REF](https://linchpiner.github.io/k8s-multi-container-pods.html).

**Comment by qiwzhang** [comment]
I see, all containers in a pod share  same IP address and port space. Thanks for the reference. 

In this case, we need to expose a flag for users to change ads port

**Comment by zhaytee** [comment]
We do plan to switch to a multi-Deployment strategy, but until we do, this could help us out a lot. Thank you!

**Comment by nareddyt** [comment]
Hi @TAOXUY and @qiwzhang, a slightly different idea:

Why don't we change ADS to use unix domain sockets instead of an TCP/IP port? Then we won't introduce internal implementation detail, and it will reduce the number of flags / configuration complexity.

Currently, we use an `core.SocketAddress` in our Envoy bootstrap config. We can change that to [core.Pipe](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/core/address.proto#core-pipe) instead.

https://github.com/GoogleCloudPlatform/esp-v2/blob/96c61ffd01f1c6eb0a90aa96aa8d1e0143f147dd/src/go/bootstrap/ads/bootstrap_test.go#L97

And then config manager listens on that port using `net.Listen` here. We can listen on a unix domain socket pretty easily - [example](https://stackoverflow.com/a/4759231/4402434).

https://github.com/GoogleCloudPlatform/esp-v2/blob/96c61ffd01f1c6eb0a90aa96aa8d1e0143f147dd/src/go/configmanager/main/server.go#L59

Maybe we can also follow the same approach for the [Local Token Access Server](https://github.com/GoogleCloudPlatform/esp-v2/blob/96c61ffd01f1c6eb0a90aa96aa8d1e0143f147dd/src/go/options/configgenerator.go#L121) that TokenSubscriber uses? Doable in config manager side, not sure what would need to change in TokenSubscriber though.

**Comment by qiwzhang** [comment]
I am afraid that using UDS may have same issue.   All containers in a pod may share same file system, but I am not sure.

**Comment by nareddyt** [comment]
Right, but the chance of a port conflict is then minimal. Then we don't need to expose more flags to allow changing the port.

If you don't mind adding extra flags, then we can just keep the original solution.

**Comment by qiwzhang** [comment]
What should be the UDS file path?  If we choose a fixed UDS file-path,  and if all containers in a pod share the same file namespace,  they will conflict with each other.   But I am not sure about this.  It seems they only share same IPC namespace, not file system. 

Or,  we could generate a random temporarily file path for UDS file path for each container. 

Overall,  I like the idea to use UDS.  We just have to solve some problems.  e.g. permission problem. We run configMgr and Envoy as non-root user,  will it has permission to create/read such file?

**Comment by TAOXUY** [comment]
The UDS sounds good to me.

So far, I see the file system is not shared. I believe we can add files and setup their permissions correctly when building dockers. 

As for generating temp files in the runtime, before discussing its feasibility, do we need this considering ESPv2 running in a stand-alone container?

**Comment by qiwzhang** [comment]
If file system is not shared across containers in a pod,  then we can use fixed UDS file path.

**Comment by nareddyt** [comment]
I will start taking a look at this, hopefully will be ready for the next release.
