### ISSUE TITLE
Authorization header backwards compatability

### ISSUE THREAD

**Issue by sukolenvo** [GoogleCloudPlatform/esp-v2#400]
Esp v1 accepts authorization in both  formats.
Header: `Authorization: <secret_token>`
Header: `Authorization: Bearer <secret_token>`
Relevant [code](https://github.com/cloudendpoints/esp/blob/42ae4da66a694373b77e3a5dab3da9c406cc08c3/src/api_manager/check_auth.cc#L181):
```
  if (auth_header.size() <= bearer_len ||
      auth_header.compare(0, bearer_len, kBearer) != 0) {
    // Authorization header is not long enough, or authorization header does
    // not begin with "Bearer ", set auth_token_ to the whole string.
    auth_token_ = auth_header;            // <- here we treat whole value of Authorization header as token
    return;
  }
```

But esp v2 accepts authorization only with Bearer prefix (at least by default). From JWT Authn Filter config:

```json
    "providers": {
      "firebase": {
        "issuer": "https://securetoken.google.com/pi-gcp",
        "audiences": [],
        "remoteJwks": {},
        "forward": true,
        "fromHeaders": [
          {
            "name": "Authorization",
            "valuePrefix": "Bearer "
          },
          {
            "name": "X-Goog-Iap-Jwt-Assertion"
          }
        ],
        "fromParams": [
          "access_token"
        ],
        "forwardPayloadHeader": "X-Endpoint-API-UserInfo",
        "payloadInMetadata": "jwt_payloads"
      },
```

Maybe its worth to add note about this to https://cloud.google.com/endpoints/docs/openapi/migrate-to-esp-v2

**Comment by TAOXUY** [comment]
Hi sukolenvo@,

Thanks for reporting this setting mismatch. I agree we need to add this in our jwt locations. I will fix it quickly.

**Comment by TAOXUY** [comment]
Hi sukolenvo@

I don't think we have an easy way to make such default jwt locations by configing jwt_authn filter, which is the upstream envoy filter we are depending on.

The [jwt_authn filter](https://github.com/envoyproxy/envoy/blob/bd73f3c4da0efffb2593d7c9ecf87788856dc052/test/extensions/filters/http/jwt_authn/authenticator_test.cc#L205) requires all the found tokens are verified, instead of only verifying the first found token in ESP. If we put `Authorization:` also as a default jwt location, for the case `Authorization: Bearer valid-token`, it will be failed as `Bearer valid-token` will be validated as a token along with `valid-token`. 

On the other hand, there is a way to work around by setting custom jwt locations:
- if you are http users, set custom jwt location by the [`x-goog-jwt-location`](https://cloud.google.com/endpoints/docs/openapi/openapi-extensions#x-google-jwt-locations) by 
```
x-google-jwt-locations:
  # Expect header "Authorization": "<TOKEN>"
  - header: **"Authorization"**
```
- if you are grpc users, set custom jwt locations in the [grpc yaml config](https://cloud.google.com/endpoints/docs/grpc-service-config/reference/rpc/google.api#authentication) under [Authentication.providers.jwt_locations](https://github.com/googleapis/googleapis/blob/1d641ec6515408e9919402a4be70ff361f65ebbf/google/api/auth.proto#L168)
```
 jwt_locations:
 - header: Authorization
```

Considering this is not a commonly recognized protocol like `Authorization: Bearer` and there is a workaround approach, I think we won't fix this gap in our side. WDYT, @qiwzhang ?

**Comment by qiwzhang** [comment]
Yes,  agreed. In ESPv2, it is not easy to fall back to use "Authorization: JWT-token".  I think we need to document such different between v1 and v2 in our migration [guide](https://cloud.google.com/endpoints/docs/openapi/migrate-to-esp-v2 
)  

If users really want to extract Jwt token from the authorization header without "Bearer " prefix,  they have to use x-google-jwt-location to specify it.

**Comment by sukolenvo** [comment]
Hi @TAOXUY , I thought so. Behaviour in esp-1 doesn't look intentional to me. I mentioned this as we spent quite some time trying to understand why after switching from esp-v1 to esp-v2 part of requests were denied. Maybe it will be helpful for somebody else.

**Comment by TAOXUY** [comment]
@sukolenvo, @qiwzhang, I will update our migration doc to make it clear.

**Comment by TAOXUY** [comment]
The doc change has been submitted and it should be visible soon.
