### ISSUE TITLE
503 returned for OPTIONS when ESPv2 handles CORS

### ISSUE THREAD

**Issue by gdollardollar** [GoogleCloudPlatform/esp-v2#465]
Hello!

There is a weird behavior with the OPTIONS Request when ESPv2 is handling cors (not forwarded to the backend).

If the request has valid `origin` and `Access-Control-Request-Method` headers then a 200 is returned and the logs look ok.

However if it does not:
- the route returns a 503 with:
```json
{
  "message": "upstream connect error or disconnect/reset before headers. reset reason: connection failure",
  "code": 503
}
```
- the debug logs show that the gateway tried to connect to `127.0.0.1:8082` which failed (hence the message)

I am not a super pro of CORS. Is that expected behavior?

If I enable `allowCors: True`, it works as expected.

Thanks

**Comment by qiwzhang** [comment]
Here is ESP CORS [document](https://cloud.google.com/endpoints/docs/openapi/support-cors) 

There are two ways to handle CORS;  1) ESPv2 proxy handle it,  or 2) pass to your backend to handle it.  You choose one, but not both.

1) As documented [here](https://cloud.google.com/endpoints/docs/openapi/support-cors#handle_cors_with_or),  if your backend doesn't handle CORS,  you have to set CORS [flags](https://cloud.google.com/endpoints/docs/openapi/specify-esp-v2-startup-options#cors) to tell ESPv2 to handle it.

2)  If your backend can handle CORS,  you just need to configure ESPv2 to bypass all CORS to your backend.  ESPv2 will not handle it, your backend will handle it.  As documented [here](https://cloud.google.com/endpoints/docs/openapi/support-cors#handle_cors_in_your_backend_application), you need to add following to your config

```
x-google-endpoints:
- name: "my-cool-api.endpoints.my-project-id.cloud.goog"
  allowCors: True
```

For 1),   a CORS preflight mush be a `OPTIONS` http method with valid `origin` and `Access-Control-Request-Method`, otherwise,  it will not be handled.

**Comment by qiwzhang** [comment]
Cloud Endpoint CORS [document](https://cloud.google.com/endpoints/docs/openapi/support-cors) is updated.

**Comment by nareddyt** [comment]
@qiwzhang should we reject `OPTIONS` request that don't set `Access-Control-Request-Method` in the router?

HTTP 503 is very difficult to debug. We can return a 4xx with a nice error code.

**Comment by gdollardollar** [comment]
@qiwzhang Thanks for the updated documentation. I was not using both, more like either. I was just surprised when I received a 503 for an invalid request.
There was also an attempted connection to 127.0.0.1:8082 when the options was invalid, which seemed a bit odd?

**Comment by qiwzhang** [comment]
Hi @nareddyt  

We can create a route entry with 
```
http_method==OPTIONS && (!origin_header || !access_control_request_method_header) 
```
to response with 400 with such error: 
CORS preflights request must have both origin and access_control_request_method headers
