### ISSUE TITLE
Problem with adding headers

### ISSUE THREAD

**Issue by krasnikov-andrew** [GoogleCloudPlatform/esp-v2#641]
I use ESPv2_ARGS to pass options as described [here](https://cloud.google.com/endpoints/docs/openapi/specify-esp-v2-startup-options#modification). I use `--add_response_header` and it's works as expected with other headers. But I need to pass `Strict-Transport-Security=max-age=31536000;` and that header contains `=` in body. That symbol ruins key=value parser and causes error:
`fail to initialize config manager: fail to make a snapshot, makeHttpConnectionManagerRouteConfig got err: invalid header: strict-transport-security=max-age=31536000. should be in key=value format."`

Is there are any ways to escape that character? I have tried to use ^, % and \

**Comment by qiwzhang** [comment]
Could you check with this flag `--enable_strict_transport_security`?

Since you are using ESPv2_ARGS, I assume you deploys ESPv2 in Cloud Run and your backend is remote one.  Even the flag text says the flag only work for local backend specified by `--backend` flag.   But I checked the code, it seems that it should work with remote backend too.    Could you try it?

**Comment by qiwzhang** [comment]
Just local unit tested it,  not end-to-end test,  it should work for remote backends too.
