### ISSUE TITLE
ESPv2/v1 url issue

### ISSUE THREAD

**Issue by gombasp** [GoogleCloudPlatform/esp-v2#727]
Hi,

as part of our update to ESPv2 we found following problem:

Please see this part of our proto file:

type: google.api.Service
config_version: 3
 
http:
  rules:
  - selector: endpoints.customer.CustomerService.UpdateCustomer
    patch: /customer/customers:update
    body: "*"

Honestly im not completly sure why my predecessors defined the url for the patch like /customer/customers:update. But what is sure, that with ESPv1 you could do a patch request with url like /customer/customers:update AND /customer/customers/update - both worked and executed the same update function.
However if defined like above, ESPv2 would only accept the url as defined, so /customer/customers:update.
As different clients seem to be using different urls we would be happy if there would be a way to have both of them working, as before. Is that possible in some way?
Of course i can duplicate them so that we have it with / and : as well, but im wondering if there might be some flag or any other option to solve this.

Regards, 

Peter

**Comment by nareddyt** [comment]
Classic case of [Hyrum's Law](https://www.hyrumslaw.com/) :)
The previous behavior was probably a bug in ESPv1, and ESPv2 fixes it.
Though I'm not sure exactly what component the bug was in or when it was fixed.

AFAIK we do not have any option to revert back to the buggy behavior. Generally we don't want to match URLs to things outside the spec, as it makes it harder for other developers to reason about. And it introduces many other edge cases + security concerns.

I recommend you go ahead and duplicate the config to include `/customer/customers:update` - it's an easy fix on your end and does not require any change in your clients.

(Assign to @TAOXUY to verify the above is correct)

**Comment by gombasp** [comment]
Hi,

so what would be your suggestion? Is the v1 behaviour still considered a bug? However for us its still a feature... :)
Can we expect v2 to work the same or thats out of question?

Thx, 
Peter

**Comment by nareddyt** [comment]
I recommend you go ahead and duplicate the config to include `/customer/customers/update` - it's an easy fix on your end and does not require any change in your clients.

**Comment by nareddyt** [comment]
We do not plan to modify ESPv2 to have this change. It is a bug and can lead to misuse.
