### ISSUE TITLE
Docker serverless build script script failing.

### ISSUE THREAD

**Issue by haensl** [GoogleCloudPlatform/esp-v2#734]
Hi,

I'm using the [`docker/serverless/gcloud_build_image`](https://github.com/GoogleCloudPlatform/esp-v2/blob/master/docker/serverless/gcloud_build_image) script to build and deploy endpoint configurations.  This worked great so far, however, with the latest change #730 the `mktemp` command has started failing. 

My solution for now is to pin to the previous commit and I'm not entirely sure the error is not on my side. My CI pipeline runs the script from within a `docker:stable` container with necessary utilities (e.g. `gcloud-cli`) installed and worked fine until this merge and continues to work with the commit before #730.

The error thrown:

`mktemp: Invalid argument`

**Comment by qiwzhang** [comment]
This is exactly what https://github.com/GoogleCloudPlatform/esp-v2/pull/730 wants to fix.  The command `(mktemp -d /tmp/docker.XXXX`  always fails in your CI container.  But before the fix, the script is not checking the error, "cd" cmd is no-op and the downloaded service config will be in your current folder, instead of "/tmp" which was considered as a risk if the host is shared. 

Could you "exec" into your CI container to see what format of "mktemp" cmd can be used?  Maybe you can manually fix the script for your case?

**Comment by haensl** [comment]
After digging deeper, I've found [this issue](https://github.com/srvrco/getssl/issues/612) pointing out that the `mktemp` command shipped with Alpine (and therefore `docker:stable`) differs from the GNU one. Installing the GNU `mktemp` resolves all issues with the script.

For anyone ending up here: the solution is `apk add coreutils`.
