### ISSUE TITLE
Prevent headers overwriting.

### ISSUE THREAD

**Issue by lucasvazq** [GoogleCloudPlatform/esp-v2#784]
If the client sends the `x-envoy-original-path` header, the one defined by Google's ESPv2 service is overwritten.

It would be nice to prevent client-side writing by some configuration (if it doesn't exist yet).

**Comment by nareddyt** [comment]
Interesting, I was not aware of this. Some follow-up questions:

- Are you using OpenAPI HTTP backend, or gRPC backend?
- Is it HTTP client or gRPC client?
- Your backend is the one reading the `x-envoy-original-path` header, correct? Why does your backend need the original path?

**Comment by lucasvazq** [comment]
OpenAPI HTTP and HTTP client.

We use that header to make some validations.
Maybe it's not the ideal way to validate something and we should change it, with the team we really think about it, but I still found it interesting that a user can override this header. In the end, the header is useful for something, that's why it is there, either for metadata or validations, and if the client that consumes the endpoint can overwrite it, it can alter the data that ends up being registered/traced/validated.

**Comment by nareddyt** [comment]
> In the end, the header is useful for something, that's why it is there, either for metadata or validations

A little unrelated, but might be a case of https://www.hyrumslaw.com/ :)

The header is mostly there for debugging and logging purposes. It was never intended to be validated by the backend or used for securing access.  

In fact we only have 1 integration test that verifies the header. The test is only verifying the header value in observability-related access logs. https://github.com/GoogleCloudPlatform/esp-v2/search?q=x-envoy-original-path

> If the client sends the `x-envoy-original-path` header, the one defined by Google's ESPv2 service is overwritten.

I do think this is a valid concern. I looked through the code and it's not obvious why this is occuring. All our code is explicitly overriding the client's header value.

It's possible that ESPv2 is only setting the header for some specific paths, and not setting it for other paths. Did you verify your client can overwrite the header value on ALL paths? Or did you only notice it on some paths?

Regardless, I strongly suggest you move away from using this header for validation, due to the lack of testing mentioned above.

**Comment by lucasvazq** [comment]
We haven't really done much testing, we just noticed that it was an overridable value and we were surprised. We made few inquiries sincerely.

Thank you very much for your answer, for your time and also for your advice! :pray: :smile:

**Comment by lucasvazq** [comment]
I had fun reading about Hyrum's Law. Thanks for that!
It has a really interesting point, it even describes certain behaviors that we usually have as consumers of interfaces (not necessarily of software).
