### ISSUE TITLE
Major Security Vulnerabilities

### ISSUE THREAD

**Issue by mykhailo-kosiuk-telus** [GoogleCloudPlatform/esp-v2#871]
Since the last release on 2023.10.17 a bunch of high severity security vulnerabilities have been detected.
At least issues marked with High/Critical severity have to be fixed. The amount and severity of security issues makes the image quite vulnerable even though it's meant to be used inside of GCP infrastructure.
Our team is facing the risk of security compliance failure because of these vulnerabilities, please fix them as soon as it is possible.
![image](https://github.com/GoogleCloudPlatform/esp-v2/assets/78373998/af905290-2ac4-42ed-9df9-ff477ef6069a)

The following should be fixed automatically with the new release since the base alpine image already has these `openssl` issues fixed with new package revision `3.1.4 r0`/`3.1.4 r1`. [alpine 3.18 digest](https://hub.docker.com/layers/library/alpine/3.18/images/sha256-5ece42cd6ca30ec1a4cc5e1e10a260ad4906e1d4588ae0ef486874d72b3857ad?context=explore)
- CVE-2023-5678
- CVE-2023-5363 (High)

All `go` issues below are fixed by version `1.20.12` according to Artifcat Registry scan. Again these should probably be fixed automatically since go.mod specifies version `1.20` and just requires new patches. Probably requires an update [here](https://github.com/GoogleCloudPlatform/esp-v2/blob/a095b7bbd9174a3473956a6cfcd9e33928e39055/docker/Dockerfile-prow-env#L54C25-L54C25)
- [CVE-2023-39323](https://nvd.nist.gov/vuln/detail/CVE-2023-39323) (Critical)
- [CVE-2023-45285](https://nvd.nist.gov/vuln/detail/CVE-2023-45285) (High)
- [CVE-2023-44487](https://nvd.nist.gov/vuln/detail/CVE-2023-44487) (High)
- [CVE-2023-39325](https://github.com/advisories/GHSA-4374-p667-p6c8) (High)
- [CVE-2023-39326](https://nvd.nist.gov/vuln/detail/CVE-2023-39326) 
- [CVE-2023-39319](https://nvd.nist.gov/vuln/detail/CVE-2023-39319)
- [CVE-2023-29406](https://nvd.nist.gov/vuln/detail/CVE-2023-29406)
- [CVE-2023-39318](https://nvd.nist.gov/vuln/detail/CVE-2023-39318)
- [CVE-2023-29409](https://nvd.nist.gov/vuln/detail/CVE-2023-29409)
- [CVE-2023-3978](https://github.com/advisories/GHSA-2wrh-6pvc-2jm9)

Go modules
- [GHSA-m425-mq94-257g](https://github.com/advisories/GHSA-m425-mq94-257g) - `google.golang.org/grpc` fixed in `1.56.3`
- [CVE-2023-3978](https://github.com/advisories/GHSA-2wrh-6pvc-2jm9) - `golang.org/x/net` fixed in `0.13.3`

Python packages, probably would be fixed automatically. 
- [CVE-2023-5752](https://github.com/advisories/GHSA-mq26-g339-26xf) - `pip` fixed in `23.3`
- [CVE-2022-40897](https://github.com/advisories/GHSA-r9hx-vwmv-q579) - `setuptools` fixed in `65.5.1` (High)

**Comment by nareddyt** [comment]
Thanks @mykhailo-kosiuk-telus for the report. We are aware of the vulnerability reports and are working on making a new release soon.

Keep in mind that just because the scanner detects a CVE doesn't mean ESPv2 is actual vulnerable to them. Some reasons:

- ESPv2 has components in different languages like C++, golang, and python, but only the C++ component is exposed to the end-user requests. Golang and python components are internal and never process API requests. Hence there is no way for an end-user to trigger such vulnerabilities.
- ESPv2 doesn't use every single function in the imported libraries. Many of these security vulnerabilities are in code that is not used by ESPv2.

I agree we should fix some of these vulnerabilities, like the openssl ones because those might be reachable from our C++ component. We can also consider updating golang packages, golang runtime, and python packages to make our reports clean and prevent confusion. @yaoluz

**Comment by mykhailo-kosiuk-telus** [comment]
@nareddyt thank you for this detailed answer, I was assuming many of the vulnerabilities may not be feasible for the image, I would defenitely be able to use your feedback as a justification, appreciate this. 
Having a clear vulnerability record would defenitely help though. Do you have any estimated timelines (quarter-wise is good enough) on when the new release is planned?

**Comment by yaoluz** [comment]
Hi @mykhailo-kosiuk-telus, we have published the new release 2.47.0, and the openssl vulnerability has been fixed in this release. Thanks again for reporting this issue!
